services:
  app:
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     configs:
      - source: sdconfig
        target: /usr/share/caddy/config.json
     volumes: 
      - ./site:/usr/share/caddy
  
  caddy:
    image: caddy:2.6.2
    restart: 'no'
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - dgraphnet
    ports: 
      - target: 80
        published: 8081

  db:
    # hostname: dgraph_standalone # Hardcoded in db_init entrypoint.sh
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet

  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-0812f6f
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      DGRAPH_SERVER: http://db:8080
      # SAMPLE_DATA: pubs_and_persons

  db_keywords:
    image: ghcr.io/sustainability-zhaw/keywords:sha-a05cc62
    restart: 'no'
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    environment:
      DB_URI: http://db:8080/graphql

  dspacer: 
    image: ghcr.io/sustainability-zhaw/extraction-dspace:sha-d32cad4
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_keywords:
        condition: service_completed_successfully 
    environment: 
      TARGET_HOST: https://digitalcollection.zhaw.ch
      DB_HOST: http://db:8080
      LIMIT_BATCH: 5

  db_browser:
    image: dgraph/ratel:v21.12.0
    restart: 'no'
    networks:
      - dgraphnet
    # ports:
    #   - '8000:8000'
  
  gql_browser: 
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     volumes: 
      - ./gqldev:/usr/share/caddy

networks:
  dgraphnet:

configs:
  caddyfile:
    file: ./contrib/Caddyfile
  sdconfig:
    file: ./contrib/dashboard_config.json
