services:
  app:
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     configs:
      - source: sdconfig
        target: /usr/share/caddy/config.json
     volumes: 
      - ./site:/usr/share/caddy

  db:
    # hostname: dgraph_standalone # Hardcoded in db_init entrypoint.sh
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet

  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-3ab74a6
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      TIMEOUT: 20
      DGRAPH_SERVER: http://db:8080

  db_keywords:
    image: ghcr.io/sustainability-zhaw/keyword-webhook:sha-f014fde
    # image: sdg/keywords:t08
    restart: 'no'
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    configs:
      - source: kwconfig
        target: /etc/app/config.json

  #  # environment:
  #  #   DB_URI: http://db:8080/graphql

  dspacer: 
    image: ghcr.io/sustainability-zhaw/extraction-dspace:sha-e48a854
    # image: dspacer:t00002
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    configs:
      - source: dcconfig
        target: /etc/app/config.json

  adresolver: 
    image: ghcr.io/sustainability-zhaw/ad-resolver:sha-b73cba8
    # image: adr:t00004
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully
    env_file:
      - ./contrib/ad_config.env 

  indexer: 
    image: ghcr.io/sustainability-zhaw/sdg-indexer:sha-5419011
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_keywords:
        condition: service_completed_successfully
    environment:
      BATCH_INTERVAL: 
      DB_HOST: db:8080
      
  # DEV ENVIRONMENT COMPONENTS
  # These tools provide access to query browsers and the reverse proxy

  caddy:
    image: caddy:2.6.2
    restart: 'no'
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - dgraphnet
    ports: 
      - target: 80
        published: 8080
  
  db_browser:
    image: dgraph/ratel:v21.12.0
    restart: 'no'
    networks:
      - dgraphnet
    # ports:
    #   - '8000:8000'
  
  gql_browser: 
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     volumes: 
      - ./contrib/graphiql:/usr/share/caddy

networks:
  dgraphnet:

configs:
  caddyfile:
    file: ./contrib/Caddyfile
  sdconfig:
    file: ./contrib/dashboard_config.json
  dcconfig:
    file: ./contrib/digital_collection.json
  kwconfig:
    file: ./contrib/kwconfig.json

