services:
  app:
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     configs:
      - source: sdconfig
        target: /usr/share/caddy/config.json
     volumes: 
      - ./site:/usr/share/caddy
  
  caddy:
    image: caddy:2.6.2
    restart: 'no'
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - dgraphnet
    ports: 
      - target: 80
        published: 8081

  db:
    # hostname: dgraph_standalone # Hardcoded in db_init entrypoint.sh
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet
    ports:
      - '8080:8080'
      - '9080:9080'

  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-2016e66
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      DGRAPH_SERVER: http://sustainability-dashboard-db-1:8080
      SAMPLE_DATA: pubs_and_persons

  dspacer: 
    image: ghcr.io/sustainability-zhaw/extraction-dspace:sha-
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    environment: 
      DGRAPH_SERVER: http://sustainability-dashboard-db-1:8080
      BATCH_SIZE: 10
      LIMIT_RUN: 1
      AD_HOST: digitalcollection.zhaw.ch

  db_browser:
    image: dgraph/ratel:v21.12.0
    restart: 'no'
    networks:
      - dgraphnet
    ports:
      - '8000:8000'

networks:
  dgraphnet:

configs:
  caddyfile:
    file: ./contrib/Caddyfile
  sdconfig:
    file: ./contrib/dashboard_config.json
